config/routes.rb
Rails.application.routes.draw do
  root "todos#index"

  delete "/todos", to: "todos#delete", as: "todos_delete"

  delete "/task", to: "todos#delete_one", as: "task_delete"

  get "/todos", to: "todos#index", as: "todos" # the "as:" is naming the route to have rails allow todos_path   ... also best practice to put the as: in the get

  post "/todos", to: "todos#create"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = session[:todos] ||= []
    # binding.pry
  end
  def create
    #add a todo to the session[:todos]
    session[:todos] << params[:task]
    redirect_to todos_path
  end
  def delete
    #clear the session[:todos] all todos
    session[:todos] = []
    redirect_to todos_path
  end
  #bonus
  def delete_one
    session[:todos].delete_if {|x| x == params["format"] }
    # without explicityly passing a value from the form, 
    #delete specific todo
    redirect_to todos_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>To do via session cookies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body class = "container text-center">
<h2>To do via session cookies. WDI-16 Week 7, Day 2</h2>
<% flash.each do |key, value| %>
  <% if key == "notice" %>
    <%= content_tag :div, value, class: "text-center alert alert-warning" %>
  <% elsif key == "alert" %>
    <%= content_tag :div, value, class: "text-center alert alert-danger" %>
  <% else %>
    <%= content_tag :div, value, class: "text-center alert alert-success" %>
  <% end %>
<% end %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/todos/index.html.erb
<h1>Current task list:</h1>

<ol>
  <% @todos.each do |task| %>
    <li>
      <%= task %>
      &nbsp;
      <%= link_to "Completed", task_delete_path(task), method: :delete %>
    </li>
  <% end %>
</ol>

<%= form_tag(todos_path) do %>
  <p>
    <%= label_tag(:task) %>
    <%= text_field_tag(:task, nil, autofocus: true) %>
    <%= submit_tag "Add"%>
  </p>
<% end %>

<%= button_to "Delete All Tasks", todos_delete_path, :method => "delete" %>

<!--
button to delete
 -->